// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUCkd4tIAP_LOBALJj-xVmFgIysXaMD_4',
    appId: '1:560623009136:web:22f4fed6f85cad2651e3b5',
    messagingSenderId: '560623009136',
    projectId: 'psychology-app-dd5e9',
    authDomain: 'psychology-app-dd5e9.firebaseapp.com',
    storageBucket: 'psychology-app-dd5e9.firebasestorage.app',
    measurementId: 'G-X1HGG85KRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw2d_HCbcuzOqVvyNy_rAktrPgx1isrwg',
    appId: '1:560623009136:android:4d7ebaebb3e8747651e3b5',
    messagingSenderId: '560623009136',
    projectId: 'psychology-app-dd5e9',
    storageBucket: 'psychology-app-dd5e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbpE_QbubOpacSOMv4Dw4H-5sP4SroqEQ',
    appId: '1:560623009136:ios:f813e939848b6a4951e3b5',
    messagingSenderId: '560623009136',
    projectId: 'psychology-app-dd5e9',
    storageBucket: 'psychology-app-dd5e9.firebasestorage.app',
    iosBundleId: 'com.example.psyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbpE_QbubOpacSOMv4Dw4H-5sP4SroqEQ',
    appId: '1:560623009136:ios:f813e939848b6a4951e3b5',
    messagingSenderId: '560623009136',
    projectId: 'psychology-app-dd5e9',
    storageBucket: 'psychology-app-dd5e9.firebasestorage.app',
    iosBundleId: 'com.example.psyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUCkd4tIAP_LOBALJj-xVmFgIysXaMD_4',
    appId: '1:560623009136:web:bfad219607eeb27951e3b5',
    messagingSenderId: '560623009136',
    projectId: 'psychology-app-dd5e9',
    authDomain: 'psychology-app-dd5e9.firebaseapp.com',
    storageBucket: 'psychology-app-dd5e9.firebasestorage.app',
    measurementId: 'G-T90MDEW2D5',
  );
}
